#!/bin/sh


if test "`git symbolic-ref HEAD | sed -e 's:^refs/heads/::'`" = master; then
    echo "masterへの直コミット禁止"
    exit 1
fi

# if test "`git symbolic-ref HEAD | sed -e 's:^refs/heads/::'`" = develop; then
#     echo "<developへの直コミット禁止"
#     exit 1
# fi

